/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpus.Admin;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import model.UserModel;

/**
 *
 * @author lucuria
 */
public class DataPustakawan extends javax.swing.JFrame {

    final UserModel userModel = new UserModel();
    DefaultTableModel defaultTableModel;

    /**
     */
    public DataPustakawan() {
        initComponents();
        initData();
        initLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Brand = new javax.swing.JLabel();
        navDataPustakawan1 = new javax.swing.JLabel();
        ActiveNav1 = new javax.swing.JPanel();
        navDataMember1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField(8);
        jLabel5 = new javax.swing.JLabel();
        txtNomorTelepon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbSearchBuku = new javax.swing.JComboBox<>();
        searchBuku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        searchAlert = new javax.swing.JLabel();
        DataPustakawanAlert = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(137, 2, 185));

        Brand.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        Brand.setForeground(new java.awt.Color(255, 255, 255));
        Brand.setText("Perpustakaan");

        navDataPustakawan1.setFont(new java.awt.Font("Cantarell", 0, 27)); // NOI18N
        navDataPustakawan1.setForeground(new java.awt.Color(255, 255, 255));
        navDataPustakawan1.setText("Data Member");
        navDataPustakawan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                navDataPustakawan1MouseReleased(evt);
            }
        });

        ActiveNav1.setBackground(new java.awt.Color(204, 0, 204));

        navDataMember1.setFont(new java.awt.Font("Cantarell", 0, 27)); // NOI18N
        navDataMember1.setForeground(new java.awt.Color(255, 255, 255));
        navDataMember1.setText("Data Pustakawan");

        javax.swing.GroupLayout ActiveNav1Layout = new javax.swing.GroupLayout(ActiveNav1);
        ActiveNav1.setLayout(ActiveNav1Layout);
        ActiveNav1Layout.setHorizontalGroup(
            ActiveNav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActiveNav1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navDataMember1)
                .addGap(60, 60, 60))
        );
        ActiveNav1Layout.setVerticalGroup(
            ActiveNav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActiveNav1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navDataMember1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(navDataPustakawan1)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(ActiveNav1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Brand)
                .addGap(18, 18, 18)
                .addComponent(ActiveNav1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(navDataPustakawan1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel2.setText("Nama");

        txtUsername.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        txtUsername.setMargin(new java.awt.Insets(2, 15, 2, 15));

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel3.setText("Username");

        txtNama.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        txtNama.setMargin(new java.awt.Insets(2, 15, 2, 15));

        txtAlamat.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        txtAlamat.setMargin(new java.awt.Insets(2, 15, 2, 15));

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel4.setText("Alamat");

        txtPassword.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        txtPassword.setMargin(new java.awt.Insets(2, 15, 2, 15));

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel5.setText("Password");

        txtNomorTelepon.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        txtNomorTelepon.setMargin(new java.awt.Insets(2, 15, 2, 15));

        jLabel9.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel9.setText("Nomor Telepon");

        btnTambah.setBackground(new java.awt.Color(244, 218, 254));
        btnTambah.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(244, 218, 254));
        btnSimpan.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        btnSimpan.setText("Simpan");

        btnUbah.setBackground(new java.awt.Color(244, 218, 254));
        btnUbah.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        btnUbah.setText("Ubah");

        btnHapus.setBackground(new java.awt.Color(244, 218, 254));
        btnHapus.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        btnHapus.setText("Hapus");

        btnKeluar.setBackground(new java.awt.Color(244, 218, 254));
        btnKeluar.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        btnKeluar.setText("Keluar");

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 23)); // NOI18N
        jLabel10.setText("Pencarian");

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        jLabel11.setText("Data Pustakawan");

        cmbSearchBuku.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        cmbSearchBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nama", "username", "nomor_telepon", "uid" }));

        searchBuku.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        searchBuku.setMargin(new java.awt.Insets(2, 15, 2, 15));

        tabelUser.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Username", "Password", "Alamat", "Nomor Telepon", "Uid", "Role"
            }
        ));
        jScrollPane1.setViewportView(tabelUser);

        searchAlert.setFont(new java.awt.Font("Cantarell", 0, 25)); // NOI18N
        searchAlert.setForeground(new java.awt.Color(255, 0, 0));

        DataPustakawanAlert.setFont(new java.awt.Font("Cantarell", 0, 23)); // NOI18N
        DataPustakawanAlert.setForeground(new java.awt.Color(255, 0, 0));

        txtUID.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        txtUID.setMargin(new java.awt.Insets(2, 15, 2, 15));

        jLabel6.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel6.setText("UID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchAlert))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbSearchBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBuku))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(DataPustakawanAlert)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel9)))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91)
                                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNomorTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                    .addComponent(txtUsername)
                                    .addComponent(txtPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel11)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DataPustakawanAlert)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomorTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(searchAlert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSearchBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navDataPustakawan1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDataPustakawan1MouseReleased
        new DataMember().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_navDataPustakawan1MouseReleased

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed

    }//GEN-LAST:event_btnTambahActionPerformed

    public void clearRow() {
        if (defaultTableModel.getRowCount() != 0) {
            defaultTableModel.setRowCount(0);
        }
    }

    private void initData() {
        searchAlert.setText("");

        // fetch data
        ResultSet data = this.userModel.findAll("role", "pustakawan");
        defaultTableModel = (DefaultTableModel) tabelUser.getModel();

        // clear data first
        clearRow();

        // then inject row
        this.userModel.injectRow(defaultTableModel, data);
    }

    public void addSelectedRowToinput(UserModel data) {
        txtNama.setText(data.nama);
        txtUsername.setText(data.username);
        txtPassword.setText(data.password);
        txtAlamat.setText(data.alamat);
        txtNomorTelepon.setText(data.nomor_telepon);
        txtUID.setText(data.uid);
    }

    public void getSelectedRow() {
        // place data to input
        int row = tabelUser.getSelectedRow();
        this.userModel.nama = tabelUser.getModel().getValueAt(row, 1).toString();
        this.userModel.username = tabelUser.getModel().getValueAt(row, 2).toString();
        this.userModel.password = tabelUser.getModel().getValueAt(row, 3).toString();
        this.userModel.alamat = tabelUser.getModel().getValueAt(row, 4).toString();
        this.userModel.nomor_telepon = tabelUser.getModel().getValueAt(row, 5).toString();
        this.userModel.uid = tabelUser.getModel().getValueAt(row, 7).toString();
    }

    public UserModel grabInputForm() {
        DataPustakawanAlert.setText("");

        // check if form is null
        if (txtNama.getText().equals("") || txtUsername.getText().equals("")
                && txtPassword.getText().equals("") || txtAlamat.getText().equals("")
                && txtNomorTelepon.getText().equals("") || txtUID.getText().equals("")) {

            DataPustakawanAlert.setText("Data form kosong");
            return null;
        }

        // grab all input user
        this.userModel.nama = txtNama.getText();
        this.userModel.username = txtUsername.getText();
        this.userModel.password = txtPassword.getText();
        this.userModel.alamat = txtAlamat.getText();
        this.userModel.nomor_telepon = txtNomorTelepon.getText();
        this.userModel.uid = txtUID.getText();

        return this.userModel;
    }

    public void clearInputForm() {
        txtNama.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtAlamat.setText("");
        txtNomorTelepon.setText("");
        txtUID.setText("");
    }

    public void initLayout() {
        // hide button
        btnSimpan.setEnabled(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);

        // adjust table size
        tabelUser.setRowHeight(25);
        tabelUser.getColumnModel().getColumn(0).setPreferredWidth(1);
        tabelUser.getColumnModel().getColumn(1).setPreferredWidth(130);
        tabelUser.getColumnModel().getColumn(2).setPreferredWidth(230);
        tabelUser.getColumnModel().getColumn(3).setPreferredWidth(1);
        tabelUser.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabelUser.getColumnModel().getColumn(5).setPreferredWidth(1);
        tabelUser.getColumnModel().getColumn(6).setPreferredWidth(40);
        tabelUser.getColumnModel().getColumn(7).setPreferredWidth(40);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPustakawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPustakawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPustakawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPustakawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPustakawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActiveNav1;
    private javax.swing.JLabel Brand;
    private javax.swing.JLabel DataPustakawanAlert;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbSearchBuku;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel navDataMember1;
    private javax.swing.JLabel navDataPustakawan1;
    private javax.swing.JLabel searchAlert;
    private javax.swing.JTextField searchBuku;
    private javax.swing.JTable tabelUser;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomorTelepon;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
